import { defineGraphicRuntime } from '@/features/graphic-generation/graphic-runtimes/define-graphic-runtime'
import type { ControllerControlDefinition } from '@/modules/studio-controller/controller-definition'

export const RADIAL_FLUTED_GLASS_DEFAULT_INPUT = {
	source: { x: -0.96, y: 0 },
	bloomColor: '#3dff8a',
	rayColor1: '#000e06',
	rayColor2: '#004218',
	rayColor3: '#008533',
	rayColor4: '#1af087',
	rayColor5: '#e0fff0',
	rayBackgroundColor: '#000302',
	rayBloom: 0.42,
	rayIntensity: 0.82,
	rayDensity: 0.34,
	raySpotty: 0.66,
	rayMidSize: 0.22,
	rayMidIntensity: 0.72,
	speed: 0.72,
	frameOffsetMs: 0,
	rayScale: 1,
	rayRotation: -6,
	radialFalloff: 0.9,
	radialFlowSpeed: 0.045,
	pulseIntensity: 0.62,
	pulseSpeed: 0.36,
	pulseDensity: 1.2,
	pulseWidth: 0.16,
	glassSize: 0.82,
	glassAngle: 8,
	glassOriginOffset: { x: -0.035, y: 0.055 },
	glassOffset: 0,
	glassSpeed: -0.035,
	glassDrift: { x: 0.02, y: 0.042 },
	glassDriftSpeedX: 0.19,
	glassDriftSpeedY: 0.27,
	glassDistortion: 0.68,
	glassEdgeSoftness: 0.62,
	glassBlur: 0.4,
	glassScattering: 0.24,
	glassHighlights: 0.62,
	glassShadows: 0.48,
	glassSourceFadeStart: 0.08,
	glassSourceFadeEnd: 0.34,
	distortionShape: 'lens',
} as const

type RangeControl = Extract<ControllerControlDefinition, { kind: 'range' }>

function rangeControl(
	id: string,
	label: string,
	defaultValue: number,
	min: number,
	max: number,
	step = 0.01,
	display: RangeControl['display'] = { precision: 2 },
): RangeControl {
	return { id, kind: 'range', label, defaultValue, min, max, step, display }
}

function colorControl(id: string, label: string, defaultValue: string) {
	return { id, kind: 'color' as const, label, defaultValue }
}

const radialFlutedGlassRuntimeManifest = defineGraphicRuntime({
	studio: 'graphic',
	id: 'radial-fluted-glass',
	version: 1,
	name: 'Radial Fluted Glass',
	type: 'shader',
	artifacts: ['raster', 'video'],
	controller: {
		groups: [
			{
				id: 'ray-palette',
				title: 'Ray Palette',
				collapsible: true,
				defaultOpen: false,
				controls: [
					colorControl(
						'rayColor1',
						'광선 색상 1',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayColor1,
					),
					colorControl(
						'rayColor2',
						'광선 색상 2',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayColor2,
					),
					colorControl(
						'rayColor3',
						'광선 색상 3',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayColor3,
					),
					colorControl(
						'rayColor4',
						'광선 색상 4',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayColor4,
					),
					colorControl(
						'rayColor5',
						'광선 색상 5',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayColor5,
					),
					colorControl(
						'rayBackgroundColor',
						'배경 색상',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayBackgroundColor,
					),
				],
			},
			{
				id: 'rays',
				title: 'Rays',
				controls: [
					colorControl(
						'bloomColor',
						'블룸 색상',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.bloomColor,
					),
					rangeControl(
						'rayBloom',
						'블룸 강도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayBloom,
						0,
						1,
					),
					rangeControl(
						'rayIntensity',
						'광선 강도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayIntensity,
						0,
						1,
					),
					rangeControl(
						'rayDensity',
						'광선 밀도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayDensity,
						0,
						1,
					),
					rangeControl(
						'raySpotty',
						'광선 연속성',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.raySpotty,
						0,
						1,
					),
					rangeControl(
						'rayMidSize',
						'중앙광 크기',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayMidSize,
						0,
						1,
					),
					rangeControl(
						'rayMidIntensity',
						'중앙광 강도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayMidIntensity,
						0,
						1,
					),
					rangeControl('speed', '속도', RADIAL_FLUTED_GLASS_DEFAULT_INPUT.speed, 0, 2),
					rangeControl(
						'rayScale',
						'광선 스케일',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayScale,
						0.1,
						2,
					),
					rangeControl(
						'rayRotation',
						'광선 회전',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.rayRotation,
						-180,
						180,
						1,
						{ precision: 0, unit: '°' },
					),
					rangeControl(
						'frameOffsetMs',
						'프레임 오프셋',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.frameOffsetMs,
						0,
						1000,
						1,
						{ precision: 0, unit: 'ms' },
					),
				],
			},
			{
				id: 'pulse',
				title: 'Pulse',
				collapsible: true,
				defaultOpen: false,
				controls: [
					rangeControl(
						'radialFalloff',
						'감쇠',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.radialFalloff,
						0,
						3,
					),
					rangeControl(
						'radialFlowSpeed',
						'흐름 속도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.radialFlowSpeed,
						0,
						1,
					),
					rangeControl(
						'pulseIntensity',
						'펄스 강도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.pulseIntensity,
						0,
						2,
					),
					rangeControl(
						'pulseSpeed',
						'펄스 속도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.pulseSpeed,
						0,
						2,
					),
					rangeControl(
						'pulseDensity',
						'펄스 밀도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.pulseDensity,
						0.1,
						4,
					),
					rangeControl(
						'pulseWidth',
						'펄스 폭',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.pulseWidth,
						0.01,
						0.5,
					),
				],
			},
			{
				id: 'glass',
				title: 'Glass',
				controls: [
					rangeControl(
						'glassSize',
						'플루트 크기',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassSize,
						0,
						1,
					),
					rangeControl(
						'glassDistortion',
						'유리 왜곡',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassDistortion,
						0,
						1,
					),
					{
						id: 'distortionShape',
						kind: 'select',
						label: '왜곡 형태',
						defaultValue: RADIAL_FLUTED_GLASS_DEFAULT_INPUT.distortionShape,
						options: [
							{ value: 'cascade', label: 'Cascade' },
							{ value: 'flat', label: 'Flat' },
							{ value: 'contour', label: 'Contour' },
							{ value: 'lens', label: 'Lens' },
						],
					},
					rangeControl(
						'glassAngle',
						'플루트 각도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassAngle,
						-180,
						180,
						1,
						{
							precision: 0,
							unit: '°',
						},
					),
					rangeControl(
						'glassEdgeSoftness',
						'경계 부드러움',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassEdgeSoftness,
						0,
						1,
					),
					rangeControl(
						'glassBlur',
						'블러',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassBlur,
						0,
						1,
					),
					rangeControl(
						'glassScattering',
						'산란',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassScattering,
						0,
						1,
					),
					rangeControl(
						'glassHighlights',
						'하이라이트',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassHighlights,
						0,
						1,
					),
					rangeControl(
						'glassShadows',
						'그림자',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassShadows,
						0,
						1,
					),
					rangeControl(
						'glassSourceFadeStart',
						'광원 페이드 시작',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassSourceFadeStart,
						0,
						0.34,
					),
					rangeControl(
						'glassSourceFadeEnd',
						'광원 페이드 끝',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassSourceFadeEnd,
						0.34,
						1,
					),
				],
			},
			{
				id: 'glass-motion',
				title: 'Glass Motion',
				collapsible: true,
				defaultOpen: false,
				controls: [
					{
						id: 'glassOriginOffset',
						kind: 'pad',
						label: '유리 원점 오프셋',
						defaultValue: RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassOriginOffset,
					},
					rangeControl(
						'glassOffset',
						'플루트 오프셋',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassOffset,
						-2,
						2,
					),
					rangeControl(
						'glassSpeed',
						'플루트 속도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassSpeed,
						-1,
						1,
					),
					{
						id: 'glassDrift',
						kind: 'pad',
						label: '드리프트 범위',
						defaultValue: RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassDrift,
					},
					rangeControl(
						'glassDriftSpeedX',
						'드리프트 X 속도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassDriftSpeedX,
						0,
						2,
					),
					rangeControl(
						'glassDriftSpeedY',
						'드리프트 Y 속도',
						RADIAL_FLUTED_GLASS_DEFAULT_INPUT.glassDriftSpeedY,
						0,
						2,
					),
				],
			},
			{
				id: 'position',
				title: 'Position',
				controls: [
					{
						id: 'source',
						kind: 'pad',
						label: '광원',
						defaultValue: RADIAL_FLUTED_GLASS_DEFAULT_INPUT.source,
					},
				],
			},
		],
	},
} as const)

export default radialFlutedGlassRuntimeManifest
