import { defineGraphicRuntime } from '@/features/graphic-generation/graphic-runtimes/define-graphic-runtime'
import type { ControllerControlDefinition } from '@/modules/studio-controller/controller-definition'

export const LINEAR_FLUTED_GLASS_DEFAULT_INPUT = {
	source: { x: -0.62, y: 0.04 },
	sourceOffsetX: 0,
	sourceOffsetY: 0,
	bloomColor: '#2ad97a',
	rayColor1: '#001a0b',
	rayColor2: '#06381b',
	rayColor3: '#0f6b32',
	rayColor4: '#8ee34a',
	rayColor5: '#e6fff4',
	rayBackgroundColor: '#000d06',
	rayBloom: 0.24,
	rayIntensity: 0.62,
	rayDensity: 0.22,
	raySpotty: 0.86,
	rayMidSize: 0.18,
	rayMidIntensity: 0.32,
	speed: 0.62,
	frameOffsetMs: 0,
	rayScale: 1,
	rayRotation: 0,
	axisFalloff: 1.7,
	flowSpeed: 0.06,
	paletteShift: 1.2,
	paletteDrift: 0.08,
	pulseIntensity: 0.3,
	pulseSpeed: 0.28,
	pulseDensity: 0.9,
	pulseWidth: 0.22,
	glassSize: 0.92,
	ribCurve: 0.5,
	glassAngle: 0,
	glassOriginOffset: { x: 0, y: 0 },
	glassOffset: 0,
	glassSpeed: -0.02,
	glassDrift: { x: 0, y: 0.03 },
	glassDriftSpeedX: 0.19,
	glassDriftSpeedY: 0.27,
	glassDistortion: 0.62,
	glassEdgeSoftness: 0.55,
	glassBlur: 0.42,
	glassScattering: 0.3,
	glassHighlights: 0.72,
	glassShadows: 0.74,
	distortionShape: 'lens',
} as const

type RangeControl = Extract<ControllerControlDefinition, { kind: 'range' }>

function rangeControl(
	id: string,
	label: string,
	defaultValue: number,
	min: number,
	max: number,
	step = 0.01,
	display: RangeControl['display'] = { precision: 2 },
): RangeControl {
	return { id, kind: 'range', label, defaultValue, min, max, step, display }
}

function colorControl(id: string, label: string, defaultValue: string) {
	return { id, kind: 'color' as const, label, defaultValue }
}

const linearFlutedGlassRuntimeManifest = defineGraphicRuntime({
	studio: 'graphic',
	id: 'linear-fluted-glass',
	version: 1,
	name: 'Linear Fluted Glass',
	type: 'shader',
	artifacts: {
		raster: {},
		video: {
			fps: [24, 30, 60],
			maxWidth: 1920,
			maxHeight: 1080,
			maxDurationSeconds: 10,
		},
	},
	controller: {
		groups: [
			{
				id: 'ray-palette',
				title: 'Ray Palette',
				controls: [
					colorControl(
						'rayColor1',
						'광선 색상 1',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayColor1,
					),
					colorControl(
						'rayColor2',
						'광선 색상 2',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayColor2,
					),
					colorControl(
						'rayColor3',
						'광선 색상 3',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayColor3,
					),
					colorControl(
						'rayColor4',
						'광선 색상 4',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayColor4,
					),
					colorControl(
						'rayColor5',
						'광선 색상 5',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayColor5,
					),
					colorControl(
						'rayBackgroundColor',
						'배경 색상',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayBackgroundColor,
					),
					rangeControl(
						'paletteShift',
						'팔레트 위상',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.paletteShift,
						0,
						4,
					),
					rangeControl(
						'paletteDrift',
						'팔레트 위상 속도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.paletteDrift,
						-1,
						1,
					),
				],
			},
			{
				id: 'rays',
				title: 'Rays',
				controls: [
					colorControl(
						'bloomColor',
						'블룸 색상',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.bloomColor,
					),
					rangeControl(
						'rayBloom',
						'블룸 강도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayBloom,
						0,
						1,
					),
					rangeControl(
						'rayIntensity',
						'광선 강도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayIntensity,
						0,
						1,
					),
					rangeControl(
						'rayDensity',
						'광선 밀도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayDensity,
						0,
						1,
					),
					rangeControl(
						'raySpotty',
						'광선 연속성',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.raySpotty,
						0,
						1,
					),
					rangeControl(
						'rayMidSize',
						'중앙광 두께',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayMidSize,
						0,
						1,
					),
					rangeControl(
						'rayMidIntensity',
						'중앙광 강도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayMidIntensity,
						0,
						1,
					),
					rangeControl('speed', '속도', LINEAR_FLUTED_GLASS_DEFAULT_INPUT.speed, 0, 2),
					rangeControl(
						'rayScale',
						'광선 스케일',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayScale,
						0.1,
						2,
					),
					rangeControl(
						'rayRotation',
						'광선 기울기',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.rayRotation,
						-180,
						180,
						1,
						{ precision: 0, unit: '°' },
					),
					rangeControl(
						'frameOffsetMs',
						'프레임 오프셋',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.frameOffsetMs,
						0,
						1000,
						1,
						{ precision: 0, unit: 'ms' },
					),
				],
			},
			{
				id: 'pulse',
				title: 'Pulse',
				controls: [
					rangeControl(
						'axisFalloff',
						'축 감쇠',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.axisFalloff,
						0,
						3,
					),
					rangeControl(
						'flowSpeed',
						'흐름 속도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.flowSpeed,
						0,
						1,
					),
					rangeControl(
						'pulseIntensity',
						'펄스 강도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.pulseIntensity,
						0,
						2,
					),
					rangeControl(
						'pulseSpeed',
						'펄스 속도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.pulseSpeed,
						0,
						2,
					),
					rangeControl(
						'pulseDensity',
						'펄스 밀도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.pulseDensity,
						0.1,
						4,
					),
					rangeControl(
						'pulseWidth',
						'펄스 폭',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.pulseWidth,
						0.01,
						0.5,
					),
				],
			},
			{
				id: 'glass',
				title: 'Glass',
				controls: [
					rangeControl(
						'glassSize',
						'플루트 크기',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassSize,
						0,
						1,
					),
					rangeControl(
						'ribCurve',
						'플루트 폭 커브',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.ribCurve,
						0.2,
						3,
					),
					rangeControl(
						'glassDistortion',
						'유리 왜곡',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassDistortion,
						0,
						1,
					),
					{
						id: 'distortionShape',
						kind: 'select',
						label: '왜곡 형태',
						defaultValue: LINEAR_FLUTED_GLASS_DEFAULT_INPUT.distortionShape,
						options: [
							{ value: 'cascade', label: 'Cascade' },
							{ value: 'flat', label: 'Flat' },
							{ value: 'contour', label: 'Contour' },
							{ value: 'lens', label: 'Lens' },
						],
					},
					rangeControl(
						'glassAngle',
						'플루트 기울기',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassAngle,
						-180,
						180,
						1,
						{
							precision: 0,
							unit: '°',
						},
					),
					rangeControl(
						'glassEdgeSoftness',
						'경계 부드러움',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassEdgeSoftness,
						0,
						1,
					),
					rangeControl(
						'glassBlur',
						'블러',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassBlur,
						0,
						1,
					),
					rangeControl(
						'glassScattering',
						'산란',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassScattering,
						0,
						1,
					),
					rangeControl(
						'glassHighlights',
						'하이라이트',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassHighlights,
						0,
						1,
					),
					rangeControl(
						'glassShadows',
						'그림자',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassShadows,
						0,
						1,
					),
				],
			},
			{
				id: 'glass-motion',
				title: 'Glass Motion',
				controls: [
					{
						id: 'glassOriginOffset',
						kind: 'pad',
						label: '유리 원점 오프셋',
						defaultValue: LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassOriginOffset,
					},
					rangeControl(
						'glassOffset',
						'플루트 오프셋',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassOffset,
						-2,
						2,
					),
					rangeControl(
						'glassSpeed',
						'플루트 속도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassSpeed,
						-1,
						1,
					),
					{
						id: 'glassDrift',
						kind: 'pad',
						label: '드리프트 범위',
						defaultValue: LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassDrift,
					},
					rangeControl(
						'glassDriftSpeedX',
						'드리프트 X 속도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassDriftSpeedX,
						0,
						2,
					),
					rangeControl(
						'glassDriftSpeedY',
						'드리프트 Y 속도',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.glassDriftSpeedY,
						0,
						2,
					),
				],
			},
			{
				id: 'position',
				title: 'Position',
				controls: [
					{
						id: 'source',
						kind: 'pad',
						label: '광원 축',
						defaultValue: LINEAR_FLUTED_GLASS_DEFAULT_INPUT.source,
					},
					rangeControl(
						'sourceOffsetX',
						'광원 X 오프셋',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.sourceOffsetX,
						-2,
						2,
					),
					rangeControl(
						'sourceOffsetY',
						'광원 Y 오프셋',
						LINEAR_FLUTED_GLASS_DEFAULT_INPUT.sourceOffsetY,
						-2,
						2,
					),
				],
			},
		],
	},
} as const)

export default linearFlutedGlassRuntimeManifest
