import { defineGraphicRuntime } from '@/features/graphic-generation/graphic-runtimes/define-graphic-runtime'
import type { ControllerControlDefinition } from '@/modules/studio-controller/controller-definition'

// 광원을 코너 끝이 아니라 프레임 안쪽에 둔다 — 스윕 회전은 광원 주변 부채꼴이 보여야 읽힌다.
export const SWEEP_FLUTED_GLASS_DEFAULT_INPUT = {
	source: { x: 0, y: 0 },
	sourceOffsetX: 0,
	sourceOffsetY: -0.3,
	bloomColor: '#3dff8a',
	rayColor1: '#000e06',
	rayColor2: '#004218',
	rayColor3: '#008533',
	rayColor4: '#1af087',
	rayColor5: '#e0fff0',
	rayBackgroundColor: '#000302',
	rayBloom: 0.2,
	rayIntensity: 0.95,
	rayDensity: 1,
	raySpotty: 0.35,
	rayMidSize: 0.4,
	rayMidIntensity: 0.7,
	speed: 0.72,
	frameOffsetMs: 0,
	rayScale: 1,
	rayRotation: -6,
	sweepSpeed: 0.12,
	radialFalloff: 0.9,
	radialFlowSpeed: 0.1,
	pulseIntensity: 0.6,
	pulseSpeed: 0.2,
	pulseDensity: 0.85,
	pulseWidth: 0.3,
	glassSize: 0.82,
	glassAngle: 8,
	glassOriginOffset: { x: -0.035, y: 0.055 },
	glassOffset: 0,
	glassSpeed: -0.035,
	glassDrift: { x: 0.02, y: 0.042 },
	glassDriftSpeedX: 0.19,
	glassDriftSpeedY: 0.27,
	glassDistortion: 0.68,
	glassEdgeSoftness: 0.62,
	glassBlur: 0.4,
	glassScattering: 0.24,
	glassHighlights: 0.62,
	glassShadows: 0.48,
	glassSourceFadeStart: 0,
	glassSourceFadeEnd: 0.4,
	distortionShape: 'lens',
} as const

type RangeControl = Extract<ControllerControlDefinition, { kind: 'range' }>

function rangeControl(
	id: string,
	label: string,
	defaultValue: number,
	min: number,
	max: number,
	step = 0.01,
	display: RangeControl['display'] = { precision: 2 },
): RangeControl {
	return { id, kind: 'range', label, defaultValue, min, max, step, display }
}

function colorControl(id: string, label: string, defaultValue: string) {
	return { id, kind: 'color' as const, label, defaultValue }
}

const sweepFlutedGlassRuntimeManifest = defineGraphicRuntime({
	studio: 'graphic',
	id: 'sweep-fluted-glass',
	version: 1,
	name: 'Sweep Fluted Glass',
	type: 'shader',
	artifacts: {
		raster: {},
		video: {
			fps: [24, 30, 60],
			maxWidth: 1920,
			maxHeight: 1080,
			maxDurationSeconds: 10,
		},
	},
	controller: {
		groups: [
			{
				id: 'ray-palette',
				title: 'Ray Palette',
				controls: [
					colorControl(
						'rayColor1',
						'광선 색상 1',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayColor1,
					),
					colorControl(
						'rayColor2',
						'광선 색상 2',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayColor2,
					),
					colorControl(
						'rayColor3',
						'광선 색상 3',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayColor3,
					),
					colorControl(
						'rayColor4',
						'광선 색상 4',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayColor4,
					),
					colorControl(
						'rayColor5',
						'광선 색상 5',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayColor5,
					),
					colorControl(
						'rayBackgroundColor',
						'배경 색상',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayBackgroundColor,
					),
				],
			},
			{
				id: 'rays',
				title: 'Rays',
				controls: [
					colorControl(
						'bloomColor',
						'블룸 색상',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.bloomColor,
					),
					rangeControl(
						'rayBloom',
						'블룸 강도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayBloom,
						0,
						1,
					),
					rangeControl(
						'rayIntensity',
						'광선 강도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayIntensity,
						0,
						1,
					),
					rangeControl(
						'rayDensity',
						'광선 밀도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayDensity,
						0,
						1,
					),
					rangeControl(
						'raySpotty',
						'광선 연속성',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.raySpotty,
						0,
						1,
					),
					rangeControl(
						'rayMidSize',
						'중앙광 크기',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayMidSize,
						0,
						1,
					),
					rangeControl(
						'rayMidIntensity',
						'중앙광 강도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayMidIntensity,
						0,
						1,
					),
					rangeControl('speed', '속도', SWEEP_FLUTED_GLASS_DEFAULT_INPUT.speed, 0, 2),
					rangeControl(
						'rayScale',
						'광선 스케일',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayScale,
						0.1,
						2,
					),
					rangeControl(
						'rayRotation',
						'광선 회전',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.rayRotation,
						-180,
						180,
						1,
						{ precision: 0, unit: '°' },
					),
					rangeControl(
						'frameOffsetMs',
						'프레임 오프셋',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.frameOffsetMs,
						0,
						1000,
						1,
						{ precision: 0, unit: 'ms' },
					),
				],
			},
			{
				id: 'sweep',
				title: 'Sweep',
				controls: [
					// 음수는 역방향 회전이다 — 광선 필드 전체가 광원을 축으로 돈다.
					rangeControl(
						'sweepSpeed',
						'스윕 속도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.sweepSpeed,
						-1,
						1,
					),
					rangeControl(
						'radialFalloff',
						'감쇠',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.radialFalloff,
						0,
						3,
					),
					rangeControl(
						'radialFlowSpeed',
						'흐름 속도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.radialFlowSpeed,
						0,
						1,
					),
					rangeControl(
						'pulseIntensity',
						'빔 강도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.pulseIntensity,
						0,
						2,
					),
					rangeControl(
						'pulseSpeed',
						'빔 위상 속도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.pulseSpeed,
						0,
						2,
					),
					rangeControl(
						'pulseDensity',
						'빔 밀도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.pulseDensity,
						0.1,
						4,
					),
					rangeControl(
						'pulseWidth',
						'빔 폭',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.pulseWidth,
						0.01,
						0.5,
					),
				],
			},
			{
				id: 'glass',
				title: 'Glass',
				controls: [
					rangeControl(
						'glassSize',
						'플루트 크기',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassSize,
						0,
						1,
					),
					rangeControl(
						'glassDistortion',
						'유리 왜곡',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassDistortion,
						0,
						1,
					),
					{
						id: 'distortionShape',
						kind: 'select',
						label: '왜곡 형태',
						defaultValue: SWEEP_FLUTED_GLASS_DEFAULT_INPUT.distortionShape,
						options: [
							{ value: 'cascade', label: 'Cascade' },
							{ value: 'flat', label: 'Flat' },
							{ value: 'contour', label: 'Contour' },
							{ value: 'lens', label: 'Lens' },
						],
					},
					rangeControl(
						'glassAngle',
						'플루트 각도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassAngle,
						-180,
						180,
						1,
						{
							precision: 0,
							unit: '°',
						},
					),
					rangeControl(
						'glassEdgeSoftness',
						'경계 부드러움',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassEdgeSoftness,
						0,
						1,
					),
					rangeControl(
						'glassBlur',
						'블러',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassBlur,
						0,
						1,
					),
					rangeControl(
						'glassScattering',
						'산란',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassScattering,
						0,
						1,
					),
					rangeControl(
						'glassHighlights',
						'하이라이트',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassHighlights,
						0,
						1,
					),
					rangeControl(
						'glassShadows',
						'그림자',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassShadows,
						0,
						1,
					),
					rangeControl(
						'glassSourceFadeStart',
						'광원 페이드 시작',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassSourceFadeStart,
						0,
						0.34,
					),
					rangeControl(
						'glassSourceFadeEnd',
						'광원 페이드 끝',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassSourceFadeEnd,
						0.34,
						1,
					),
				],
			},
			{
				id: 'glass-motion',
				title: 'Glass Motion',
				controls: [
					{
						id: 'glassOriginOffset',
						kind: 'pad',
						label: '유리 원점 오프셋',
						defaultValue: SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassOriginOffset,
					},
					rangeControl(
						'glassOffset',
						'플루트 오프셋',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassOffset,
						-2,
						2,
					),
					rangeControl(
						'glassSpeed',
						'플루트 속도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassSpeed,
						-1,
						1,
					),
					{
						id: 'glassDrift',
						kind: 'pad',
						label: '드리프트 범위',
						defaultValue: SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassDrift,
					},
					rangeControl(
						'glassDriftSpeedX',
						'드리프트 X 속도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassDriftSpeedX,
						0,
						2,
					),
					rangeControl(
						'glassDriftSpeedY',
						'드리프트 Y 속도',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.glassDriftSpeedY,
						0,
						2,
					),
				],
			},
			{
				id: 'position',
				title: 'Position',
				controls: [
					{
						id: 'source',
						kind: 'pad',
						label: '광원',
						defaultValue: SWEEP_FLUTED_GLASS_DEFAULT_INPUT.source,
					},
					rangeControl(
						'sourceOffsetX',
						'광원 X 오프셋',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.sourceOffsetX,
						-2,
						2,
					),
					rangeControl(
						'sourceOffsetY',
						'광원 Y 오프셋',
						SWEEP_FLUTED_GLASS_DEFAULT_INPUT.sourceOffsetY,
						-2,
						2,
					),
				],
			},
		],
	},
} as const)

export default sweepFlutedGlassRuntimeManifest
