import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
	server: {
		ANTHROPIC_API_KEY: z.string().min(1).optional(),
		ANTHROPIC_MODEL: z.string().min(1).optional(),
		DATABASE_URL: z.string().url(),
		EMAIL_FROM_ADDRESS: z.string().email().optional(),
		EMAIL_FROM_NAME: z.string().min(1).optional(),
		FIGMA_API_TOKEN: z.string().min(1).optional(),
		NEXT_PHASE: z.string().min(1).optional(),
		NODE_ENV: z.enum(['development', 'production', 'test']).optional(),
		PAYLOAD_DB_PUSH: z.enum(['true', 'false']).optional(),
		PAYLOAD_RUN_MIGRATIONS_ON_STARTUP: z.enum(['true', 'false']).optional(),
		PAYLOAD_SECRET: z.string().min(1),
		RESEND_API_KEY: z.string().min(1).optional(),
		S3_ACCESS_KEY_ID: z.string().min(1).optional(),
		S3_BUCKET: z.string().min(1).optional(),
		S3_REGION: z.string().min(1).optional(),
		S3_SECRET_ACCESS_KEY: z.string().min(1).optional(),
		VERCEL_URL: z.string().min(1).optional(),
	},
	client: {
		NEXT_PUBLIC_SITE_URL: z.string().url().optional(),
	},
	runtimeEnv: {
		ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
		ANTHROPIC_MODEL: process.env.ANTHROPIC_MODEL,
		DATABASE_URL: process.env.DATABASE_URL,
		EMAIL_FROM_ADDRESS: process.env.EMAIL_FROM_ADDRESS,
		EMAIL_FROM_NAME: process.env.EMAIL_FROM_NAME,
		FIGMA_API_TOKEN: process.env.FIGMA_API_TOKEN,
		NEXT_PHASE: process.env.NEXT_PHASE,
		NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
		NODE_ENV: process.env.NODE_ENV,
		PAYLOAD_DB_PUSH: process.env.PAYLOAD_DB_PUSH,
		PAYLOAD_RUN_MIGRATIONS_ON_STARTUP: process.env.PAYLOAD_RUN_MIGRATIONS_ON_STARTUP,
		PAYLOAD_SECRET: process.env.PAYLOAD_SECRET,
		RESEND_API_KEY: process.env.RESEND_API_KEY,
		S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
		S3_BUCKET: process.env.S3_BUCKET,
		S3_REGION: process.env.S3_REGION,
		S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
		VERCEL_URL: process.env.VERCEL_URL,
	},
	emptyStringAsUndefined: true,
})
