/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    rules: Rule;
    'brand-logos': BrandLogo;
    'brand-colors': BrandColor;
    'brand-typefaces': BrandTypeface;
    'application-images': ApplicationImage;
    templates: Template;
    plugins: Plugin;
    'agent-skills': AgentSkill;
    sections: Section;
    'guideline-pages': GuidelinePage;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    sections: {
      pages: 'guideline-pages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    rules: RulesSelect<false> | RulesSelect<true>;
    'brand-logos': BrandLogosSelect<false> | BrandLogosSelect<true>;
    'brand-colors': BrandColorsSelect<false> | BrandColorsSelect<true>;
    'brand-typefaces': BrandTypefacesSelect<false> | BrandTypefacesSelect<true>;
    'application-images': ApplicationImagesSelect<false> | ApplicationImagesSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    plugins: PluginsSelect<false> | PluginsSelect<true>;
    'agent-skills': AgentSkillsSelect<false> | AgentSkillsSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    'guideline-pages': GuidelinePagesSelect<false> | GuidelinePagesSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ko' | 'en') | ('ko' | 'en')[];
  globals: {
    guideline: Guideline;
  };
  globalsSelect: {
    guideline: GuidelineSelect<false> | GuidelineSelect<true>;
  };
  locale: 'ko' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * admin(전체)·manager(기준 관리)·worker(사용)
   */
  role: 'admin' | 'manager' | 'worker';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules".
 */
export interface Rule {
  id: number;
  /**
   * category.attribute 점 표기. 예: logo.min-size
   */
  key: string;
  title: string;
  category:
    | 'logo'
    | 'color'
    | 'typography'
    | 'grid'
    | 'spacing'
    | 'layout'
    | 'imagery'
    | 'illustration'
    | 'iconography'
    | 'motion'
    | 'voice'
    | 'messaging'
    | 'accessibility'
    | 'application'
    | 'misc';
  tier?: ('A' | 'B' | 'C') | null;
  executor?: ('deterministic' | 'heuristic' | 'advisory' | 'human') | null;
  scope?: ('all' | 'print' | 'screen')[] | null;
  /**
   * 값을 채운 브랜드 수 (0 = domain-default 빈 슬롯)
   */
  frequency?: number | null;
  domainDefault?: boolean | null;
  /**
   * 브랜드 값이 채워야 할 구조(요약 표기)
   */
  paramSchema?: string | null;
  scoring?: string | null;
  input?: string | null;
  notes?: string | null;
  status?: ('draft' | 'live' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-logos".
 */
export interface BrandLogo {
  id: number;
  name: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-colors".
 */
export interface BrandColor {
  id: number;
  name: string;
  hex: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-typefaces".
 */
export interface BrandTypeface {
  id: number;
  name: string;
  familyName: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-images".
 */
export interface ApplicationImage {
  id: number;
  name: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  description?: string | null;
  sourceType: 'figma' | 'file';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins".
 */
export interface Plugin {
  id: number;
  name: string;
  description?: string | null;
  pluginType: 'generator' | 'checker';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Agent가 선택해 실행할 SKILL.md 형태의 지시문입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-skills".
 */
export interface AgentSkill {
  id: number;
  /**
   * SKILL.md frontmatter의 name입니다. 예: guideline-qa
   */
  name: string;
  /**
   * 언제 이 skill을 써야 하는지 설명합니다.
   */
  description: string;
  /**
   * SKILL.md markdown 본문입니다. 실제 agent instruction으로 사용합니다.
   */
  body: string;
  /**
   * skill 선택 뒤 필요할 때 함께 읽을 reference 문서입니다.
   */
  references?:
    | {
        title: string;
        /**
         * provider skill bundle의 references/*.md에 해당하는 markdown 본문입니다.
         */
        body: string;
        /**
         * reference가 설명하거나 예시로 드는 내부 브랜드/제작 자원입니다.
         */
        assets?:
          | (
              | {
                  relationTo: 'brand-logos';
                  value: number | BrandLogo;
                }
              | {
                  relationTo: 'brand-colors';
                  value: number | BrandColor;
                }
              | {
                  relationTo: 'brand-typefaces';
                  value: number | BrandTypeface;
                }
              | {
                  relationTo: 'application-images';
                  value: number | ApplicationImage;
                }
              | {
                  relationTo: 'templates';
                  value: number | Template;
                }
              | {
                  relationTo: 'plugins';
                  value: number | Plugin;
                }
            )[]
          | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  enabled?: boolean | null;
  /**
   * agent-chat의 기본 skill 후보입니다. 하나만 true로 유지하세요.
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 가이드라인 상위 내비게이션 섹션입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  /**
   * 사이드바 상위 섹션 제목으로 표시됩니다.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * 섹션 랜딩 페이지에 표시할 선택 요약입니다.
   */
  description?: string | null;
  pages?: {
    docs?: (number | GuidelinePage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * 숫자가 낮을수록 가이드라인 내비게이션에서 먼저 표시됩니다.
   */
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 블록으로 구성하는 가이드라인 페이지입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guideline-pages".
 */
export interface GuidelinePage {
  id: number;
  /**
   * 가이드라인 화면의 페이지 제목으로 표시됩니다.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * 페이지 제목 아래에 표시할 선택 설명입니다.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 이 페이지에서 설명하거나 적용하는 규칙입니다.
   */
  rules?: (number | Rule)[] | null;
  /**
   * 사이드바 내비게이션과 URL에 사용할 상위 섹션입니다.
   */
  section: number | Section;
  /**
   * 숫자가 낮을수록 선택한 섹션 안에서 먼저 표시됩니다.
   */
  displayOrder: number;
  blocks?: (ColumnUnitBlock | MediaShowcaseBlock)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnUnitBlock".
 */
export interface ColumnUnitBlock {
  title?: string | null;
  columns?:
    | {
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | ApplicationImage;
        /**
         * 이미지 영역 뒤에 적용할 브랜드 컬러입니다.
         */
        imageBackgroundColor?: (number | null) | BrandColor;
        imageScale?: ('10' | '20' | '30' | '40' | '50' | '60' | '70' | '80' | '90' | '100') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columnUnit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaShowcaseBlock".
 */
export interface MediaShowcaseBlock {
  image?: (number | null) | ApplicationImage;
  /**
   * 이미지 영역 뒤에 적용할 브랜드 컬러입니다.
   */
  imageBackgroundColor?: (number | null) | BrandColor;
  imageScale?: ('10' | '20' | '30' | '40' | '50' | '60' | '70' | '80' | '90' | '100') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaShowcase';
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'guideline-pages';
        value: number | GuidelinePage;
      }
    | {
        relationTo: 'sections';
        value: number | Section;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'rules';
        value: number | Rule;
      } | null)
    | ({
        relationTo: 'brand-logos';
        value: number | BrandLogo;
      } | null)
    | ({
        relationTo: 'brand-colors';
        value: number | BrandColor;
      } | null)
    | ({
        relationTo: 'brand-typefaces';
        value: number | BrandTypeface;
      } | null)
    | ({
        relationTo: 'application-images';
        value: number | ApplicationImage;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'plugins';
        value: number | Plugin;
      } | null)
    | ({
        relationTo: 'agent-skills';
        value: number | AgentSkill;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'guideline-pages';
        value: number | GuidelinePage;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules_select".
 */
export interface RulesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  category?: T;
  tier?: T;
  executor?: T;
  scope?: T;
  frequency?: T;
  domainDefault?: T;
  paramSchema?: T;
  scoring?: T;
  input?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-logos_select".
 */
export interface BrandLogosSelect<T extends boolean = true> {
  name?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-colors_select".
 */
export interface BrandColorsSelect<T extends boolean = true> {
  name?: T;
  hex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-typefaces_select".
 */
export interface BrandTypefacesSelect<T extends boolean = true> {
  name?: T;
  familyName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-images_select".
 */
export interface ApplicationImagesSelect<T extends boolean = true> {
  name?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  sourceType?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins_select".
 */
export interface PluginsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  pluginType?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-skills_select".
 */
export interface AgentSkillsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  body?: T;
  references?:
    | T
    | {
        title?: T;
        body?: T;
        assets?: T;
        enabled?: T;
        id?: T;
      };
  enabled?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  pages?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guideline-pages_select".
 */
export interface GuidelinePagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  rules?: T;
  section?: T;
  displayOrder?: T;
  blocks?:
    | T
    | {
        columnUnit?: T | ColumnUnitBlockSelect<T>;
        mediaShowcase?: T | MediaShowcaseBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnUnitBlock_select".
 */
export interface ColumnUnitBlockSelect<T extends boolean = true> {
  title?: T;
  columns?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        imageBackgroundColor?: T;
        imageScale?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaShowcaseBlock_select".
 */
export interface MediaShowcaseBlockSelect<T extends boolean = true> {
  image?: T;
  imageBackgroundColor?: T;
  imageScale?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guideline".
 */
export interface Guideline {
  id: number;
  companyName: string;
  /**
   * 표지와 푸터에 표시할 문서명입니다. 예: Essenherb Brand Design Guidelines 1.0
   */
  documentTitle: string;
  /**
   * 발행 시점 표시 문구입니다. 예: Issued in February, 2026
   */
  issuedLabel?: string | null;
  /**
   * 브라우저 탭과 메타데이터에 사용할 파비콘 이미지입니다.
   */
  favicon?: (number | null) | ApplicationImage;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guideline_select".
 */
export interface GuidelineSelect<T extends boolean = true> {
  companyName?: T;
  documentTitle?: T;
  issuedLabel?: T;
  favicon?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'brand-logos';
          value: number | BrandLogo;
        } | null)
      | ({
          relationTo: 'brand-colors';
          value: number | BrandColor;
        } | null)
      | ({
          relationTo: 'brand-typefaces';
          value: number | BrandTypeface;
        } | null)
      | ({
          relationTo: 'application-images';
          value: number | ApplicationImage;
        } | null)
      | ({
          relationTo: 'templates';
          value: number | Template;
        } | null)
      | ({
          relationTo: 'plugins';
          value: number | Plugin;
        } | null)
      | ({
          relationTo: 'agent-skills';
          value: number | AgentSkill;
        } | null)
      | ({
          relationTo: 'sections';
          value: number | Section;
        } | null)
      | ({
          relationTo: 'guideline-pages';
          value: number | GuidelinePage;
        } | null);
    global?: 'guideline' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}